-- CREATE DATABASE jotcgame;

CREATE TABLE users(
uid SERIAL PRIMARY KEY,
email_id VARCHAR(64) NOT NULL,
first_name VARCHAR(64) NOT NULL,
last_name VARCHAR(64) NOT NULL,
date_of_birth DATE NOT NULL,
is_Admin BOOLEAN NOT NULL,
pwd VARCHAR(64));

CREATE TABLE jotcReq(
id SERIAL PRIMARY KEY,
email_id VARCHAR(64) NOT NULL ,
date DATE DEFAULT NOW(),
inp_len INTEGER NOT NULL,
pattern VARCHAR[] NOT NULL,
output INTEGER NOT NULL);